UsuarioLogin-MVC/UsuarioLogin-MVC/Models/EmailDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UsuarioLogin_MVC.Models
{
    public class EmailDTO
    {
        public string Para { get; set; }
        public string Asunto { get; set; }
        public string Contenido { get; set; }
    }
}

UsuarioLogin-MVC/UsuarioLogin-MVC/Models/UsuarioDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UsuarioLogin_MVC.Models
{
    public class UsuarioDTO
    {
        public string Id_Usuario { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Clave { get; set; }
        public string ConfirmarClave { get; set; }
        public bool Restablecer { get; set; }
        public bool Confirmado { get; set; }
        public string Token { get; set; }
    }
}

UsuarioLogin-MVC/UsuarioLogin-MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UsuarioLogin_MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

UsuarioLogin-MVC/UsuarioLogin-MVC/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UsuarioLogin_MVC.Datos;
using UsuarioLogin_MVC.Models;
using UsuarioLogin_MVC.Servicios;

namespace UsuarioLogin_MVC.Controllers
{
    public class InicioController : Controller
    {
        // GET: Inicio
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string email, string clave)
        {
            UsuarioDTO usuario = DBUsuario.Validar(email, UtilidadServicio.ConvertirSHA256(clave));

            if (usuario != null)
            {
                if (!usuario.Confirmado)
                {
                    ViewBag.Mensaje = $"Falta confirmar su cuenta. Se le envio un Correo a {email}";
                }
                else if (usuario.Restablecer)
                {
                    ViewBag.Mensaje = $"Se ha solicitado restablecer su cuenta, favor revise su bandeja del Correo {email}";
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

            }
            else
            {
                ViewBag.Mensaje = "No se encontraron coincidencias";
            }


            return View();
        }

        public ActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registrar(UsuarioDTO usuario)
        {
            if (usuario.Clave != usuario.ConfirmarClave)
            {
                ViewBag.Nombre = usuario.Nombre;
                ViewBag.email = usuario.Email;
                ViewBag.Mensaje = "Las contraseñas no coinciden";
                return View();
            }

            if (DBUsuario.Obtener(usuario.Email) == null)
            {
                usuario.Clave = UtilidadServicio.ConvertirSHA256(usuario.Clave);
                usuario.Token = UtilidadServicio.GenerarToken();
                usuario.Restablecer = false;
                usuario.Confirmado = false;
                bool respuesta = DBUsuario.Registrar(usuario);

                if (respuesta)
                {
                    string path = HttpContext.Server.MapPath("~/Plantilla/Confirmar.html");
                    string content = System.IO.File.ReadAllText(path);
                    string url = string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Headers["host"], "/Inicio/Confirmar?token=" + usuario.Token);

                    string htmlBody = string.Format(content, usuario.Nombre, url);

                    EmailDTO EmailDTO = new EmailDTO()
                    {
                        Para = usuario.Email,
                        Asunto = "confirmacion de Correo",
                        Contenido = htmlBody
                    };

                    bool enviado = EmailServicio.Enviar(EmailDTO);
                    ViewBag.Creado = true;
                    ViewBag.Mensaje = $"Su cuenta ha sido activada. Hemos enviado un mensaje al Correo {usuario.Email} para confirmar su cuenta";
                }
                else
                {
                    ViewBag.Mensaje = "Ocurrio un error al crear su cuenta";
                }



            }
            else
            {
                ViewBag.Mensaje = "El Correo registrado anteriormente";
            }


            return View();
        }

        public ActionResult Confirmar(string token)
        {
            ViewBag.Respuesta = DBUsuario.Confirmar(token);
            return View();
        }

        public ActionResult Restablecer()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Restablecer(string email)
        {
            UsuarioDTO usuario = DBUsuario.Obtener(email);
            ViewBag.email = email;
            if (usuario != null)
            {
                bool respuesta = DBUsuario.RestablecerActualizar(1, usuario.Clave, usuario.Token);

                if (respuesta)
                {
                    string path = HttpContext.Server.MapPath("~/Plantilla/Restablecer.html");
                    string content = System.IO.File.ReadAllText(path);
                    string url = string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Headers["host"], "/Inicio/Actualizar?token=" + usuario.Token);

                    string htmlBody = string.Format(content, usuario.Nombre, url);

                    EmailDTO EmailDTO = new EmailDTO()
                    {
                        Para = email,
                        Asunto = "Restablecer cuenta",
                        Contenido = htmlBody
                    };

                    bool enviado = EmailServicio.Enviar(EmailDTO);
                    ViewBag.Restablecido = true;
                }
                else
                {
                    ViewBag.Mensaje = "No se pudo restablecer la cuenta";
                }

            }
            else
            {
                ViewBag.Mensaje = "No se encontraron coincidencias con el Correo";
            }

            return View();
        }

        public ActionResult Actualizar(string token)
        {
            ViewBag.Token = token;
            return View();
        }

        [HttpPost]
        public ActionResult Actualizar(string token, string clave, string confirmarClave)
        {
            ViewBag.Token = token;
            if (clave != confirmarClave)
            {
                ViewBag.Mensaje = "Las contraseñas no coinciden";
                return View();
            }

            bool respuesta = DBUsuario.RestablecerActualizar(0, UtilidadServicio.ConvertirSHA256(clave), token);

            if (respuesta)
                ViewBag.Restablecido = true;
            else
                ViewBag.Mensaje = "No se pudo actualizar";

            return View();
        }
    }
}

UsuarioLogin-MVC/UsuarioLogin-MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

UsuarioLogin-MVC/UsuarioLogin-MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

UsuarioLogin-MVC/UsuarioLogin-MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

UsuarioLogin-MVC/UsuarioLogin-MVC/Views/Inicio/Actualizar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Actualizar contraseña· RodMat95</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <h1 class="text-center text-black dark:text-white m-5">RodMat95</h1>
                        @if (ViewBag.Restablecido == null)
                        {
                            <form class="mx-5" action="@Url.Action("Actualizar","Inicio")" method="post">
                                <input type="hidden" name="token" value="@ViewBag.Token" />

                                <div class="mb-3">
                                    <!--<label>Ingresar una nueva contraseña</label>-->
                                    <input type="password" class="form-control font-monospace" name="clave" placeholder="Nueva contraseña" required />
                                </div>
                                <div class="mb-3">
                                    <!--<label>Confirmar contraseña</label>-->
                                    <input type="password" class="form-control font-monospace" name="confirmarClave" placeholder="Confirmar contraseña" required />
                                </div>

                                @if (ViewBag.Mensaje != null)
                                {
                                    <div class="alert alert-danger">
                                        @ViewBag.Mensaje
                                    </div>
                                }

                                <div class="mb-3">
                                    <div class="d-grid">
                                        <button class="btn btn-primary" type="submit">Combiar contraseña</button>
                                    </div>
                                </div>


                            </form>
                        }
                        else
                        {
                            <div class="alert alert-success">
                                <p>Su contraseña fue restablecida, ahora puede ingresar a su cuenta con su nueva clave.</p>
                                <a class="btn btn-success" href="@Url.Action("Login","Inicio")">Ingresar</a>
                            </div>
                        }
                    </div>
                </div>

            </div>

        </div>
    </div>
        @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

UsuarioLogin-MVC/UsuarioLogin-MVC/Views/Inicio/Confirmar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Confirmar · RodMat95</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="col-md-4">
        @if ((bool)ViewBag.Respuesta)
        {
            <div class="alert alert-success">
                <p><b>Listo!</b>&nbsp; Su cuenta fue confirmada. Ahora puede acceder</p>
                <a class="btn btn-success" href="@Url.Action("Login","Inicio")">Ingresar</a>
            </div>
        }
        else
        {
            <div class="alert alert-danger">
                <p>No se pudo confirmar el correo</p>
            </div>
        }
    </div>
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

UsuarioLogin-MVC/UsuarioLogin-MVC/Views/Inicio/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Iniciar Sesion · RodMat95</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <h1 class="text-center text-black dark:text-white m-5">RodMat95</h1>

                        <form class="mx-5" action="@Url.Action("Login","Inicio")" method="post">

                            <div class="mb-3">
                                <!--<label for="correo" class="form-label">Correo</label>-->
                                <input type="email" class="form-control font-monospace" id="email" name="email" placeholder="Correo" required />
                            </div>
                            <div class="mb-3">
                                <!--<label for="clave" class="form-label">Contraseña</label>-->
                                <input type="password" class="form-control font-monospace" id="clave" name="clave" placeholder="Contraseña" required />
                            </div>

                            @if (ViewBag.Mensaje != null)
                            {
                                <div class="alert alert-danger">
                                    @ViewBag.Mensaje
                                </div>
                            }

                            <div class="mb-3">
                                <div class="d-grid gap-2">
                                    <button class="btn btn-primary" type="submit">Iniciar Sesión</button>
                                </div>
                            </div>
                            <div class="text-center">
                                <a class="btn btn-link text-decoration-none" href="@Url.Action("Restablecer","Inicio")">¿Olvidaste tu contraseña?</a>
                            </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <div class="text-center">
                            <label class="form-label">
                                ¿No tienes una cuenta? <a class="btn btn-link text-decoration-none" href="@Url.Action("Registrar","Inicio")">Regístrate</a>
                            </label>
                        </div>
                    </div>
                </div>

                </form>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>

UsuarioLogin-MVC/UsuarioLogin-MVC/Views/Inicio/Registrar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Registrate · RodMat95</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <h1 class="text-center text-black dark:text-white m-5">RodMat95</h1>

                        @if (ViewBag.Creado == null)
                        {
                            <form class="mx-5" action="@Url.Action("Registrar","Inicio")" method="post">

                                <div class="mb-3">
                                    <!--<label for="Nombre" class="form-label">Nombre</label>-->
                                    <input type="text" class="form-control font-monospace" id="Nombre" name="Nombre" placeholder="Nombre" value="@(ViewBag.Nombre !=null ? ViewBag.Nombre : "")" required />
                                </div>
                                <div class="mb-3">
                                    <!--<label for="Correo" class="form-label">Correo</label>-->
                                    <input type="email" class="form-control font-monospace" id="email" name="email" placeholder="Correo" value="@(ViewBag.Correo !=null ? ViewBag.Correo : "")" required />
                                </div>
                                <div class="mb-3">
                                    <!--<label for="Clave" class="form-label">Contraseña</label>-->
                                    <input type="password" class="form-control font-monospace" id="Clave" name="Clave" placeholder="Contraseña" required />
                                </div>
                                <div class="mb-3">
                                    <!--<label for="ConfirmarClave" class="form-label">Confirmar Contraseña</label>-->
                                    <input type="password" class="form-control font-monospace" id="ConfirmarClave" name="ConfirmarClave" placeholder="Confirmar Contraseña" required />
                                </div>

                                @if (ViewBag.Mensaje != null)
                                {
                                    <div class="alert alert-danger">
                                        @ViewBag.Mensaje
                                    </div>
                                }

                                <div class="mb-3">
                                    <div class="d-grid gap-2">
                                        <button class="btn btn-primary" type="submit">Regístrate</button>
                                    </div>
                                </div>

                            </form>
                        }
                        else
                        {
                            <div class="alert alert-success">
                                <p>@ViewBag.Mensaje</p>
                                <a class="btn btn-success" href="@Url.Action("Login","Inicio")">Ingresar</a>
                            </div>
                        }
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <div class="text-center">
                            <label class="form-label">
                                ¿Ya tienes una cuenta? <a class="btn btn-link text-decoration-none" href="@Url.Action("Login","Inicio")">Iniciar Sesión</a>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>

UsuarioLogin-MVC/UsuarioLogin-MVC/Views/Inicio/Restablecer.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Restablecer contraseña · RodMat95</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card mb-3">
                    <div class="card-body">
                        @if (ViewBag.Restablecido == null)
                        {
                            <form class="mx-5"  action="@Url.Action("Restablecer","Inicio")" method="post">
                                <h5 class="text-center text-black dark:text-white">¿Tienes problemas para iniciar sesión?</h5>
                                <p class="text-center text-black dark:text-white">Ingresa tu correo electrónico y te enviaremos un enlace para que recuperes el acceso a tu cuenta.</p>

                                <div class="mb-3">
                                    <!--<label for="correo" class="form-label">Correo</label>-->
                                    <input type="email" class="form-control font-monospace" id="email" name="email" placeholder="Correo" value="@(ViewBag.Correo !=null ? ViewBag.Correo : "")" required />
                                </div>

                                @if (ViewBag.Mensaje != null)
                                {
                                    <div class="alert alert-danger">
                                        @ViewBag.Mensaje
                                    </div>
                                }

                                <div class="mb-3">
                                    <div class="d-grid gap-2">
                                        <button class="btn btn-primary" type="submit">Enviar enlace de inicio de sesión</button>
                                    </div>
                                </div>
                            </form>
                        }
                        else
                        {
                            <div class="alert alert-success">
                                <p class="text-center">Su contraseña fue restablecida, le enviamos un mensaje su correo para restablecer.</p>
                                <a class="btn btn-success" href="@Url.Action("Login","Inicio")">Ingresar</a>
                            </div>
                        }
                    </div>
                    <div class="card-footer">
                        <div class="d-grid gap-2">
                            <a class="btn btn-link text-decoration-none" href="@Url.Action("Login","Inicio")">Volver al inicio de sesión</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

        @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

UsuarioLogin-MVC/UsuarioLogin-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>